import os
from datetime import datetime


def generate_report(target, scan_type, results, risk):

    reports_folder = "reports"

    if not os.path.exists(reports_folder):
        os.makedirs(reports_folder)

    filename = os.path.join(reports_folder, "scan_report.txt")

    with open(filename, "w", encoding="utf-8") as report:

        report.write("=" * 70 + "\n")
        report.write("                 NETRECON SECURITY SCAN REPORT\n")
        report.write("=" * 70 + "\n\n")

        report.write(f"Generated On : {datetime.now()}\n")
        report.write(f"Target       : {target}\n")
        report.write(f"Scan Type    : {scan_type}\n\n")

        report.write("-" * 70 + "\n")
        report.write("HOST INFORMATION\n")
        report.write("-" * 70 + "\n")

        if len(results) > 0 and "error" not in results[0]:

            report.write(f"Host Status  : {results[0]['status']}\n")
            report.write(f"Operating OS : {results[0]['os']}\n")

        report.write("\n")

        report.write("-" * 70 + "\n")
        report.write("OPEN PORTS\n")
        report.write("-" * 70 + "\n\n")

        report.write("{:<10}{:<20}{:<15}{:<20}\n".format(
            "PORT",
            "SERVICE",
            "STATE",
            "VERSION"
        ))

        report.write("=" * 70 + "\n")

        for item in results:

            if "error" in item:
                continue

            version = f"{item['product']} {item['version']}"

            report.write("{:<10}{:<20}{:<15}{:<20}\n".format(
                item["port"],
                item["service"],
                item["state"],
                version
            ))

        report.write("\n")

        report.write("-" * 70 + "\n")
        report.write("RISK ANALYSIS\n")
        report.write("-" * 70 + "\n")

        report.write(f"Risk Score : {risk['score']}\n")
        report.write(f"Risk Level : {risk['level']}\n")
        report.write(f"Open Ports : {risk['open_ports']}\n\n")

        report.write("-" * 70 + "\n")
        report.write("SECURITY RECOMMENDATIONS\n")
        report.write("-" * 70 + "\n\n")

        for recommendation in risk["recommendations"]:
            report.write(f"• {recommendation}\n")

        report.write("\n")
        report.write("=" * 70 + "\n")
        report.write("Generated by NetRecon\n")
        report.write("=" * 70 + "\n")

    return filename